name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Vite Github Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.4.0
        with:
          public_base_path: '/' 
          build_path: ./dist
          install_phase_node_env: dev
          build_phase_node_env: production
          package_manager: pnpm
          artifact_name: github-pages
          debug_mode: false
          
